"""Run the unit tests and write reviewable artifacts.

The normal command is:

    python run_tests.py

Add --experiment to refresh the small controlled experiment artifact after the
tests pass:

    python run_tests.py --experiment
"""

from __future__ import annotations

import argparse
import io
import json
import subprocess
import sys
import time
import unittest
from datetime import datetime, timezone
from pathlib import Path


def _write_test_artifact(
    artifact_dir: Path,
    result: unittest.TestResult,
    output: str,
    elapsed_seconds: float,
) -> None:
    report = {
        "created_at_utc": datetime.now(timezone.utc).isoformat(),
        "success": result.wasSuccessful(),
        "tests_run": result.testsRun,
        "failures": len(result.failures),
        "errors": len(result.errors),
        "skipped": len(result.skipped),
        "expected_failures": len(result.expectedFailures),
        "unexpected_successes": len(result.unexpectedSuccesses),
        "elapsed_seconds": elapsed_seconds,
        "output": output,
    }
    (artifact_dir / "unit_test_report.json").write_text(
        json.dumps(report, indent=2),
        encoding="utf-8",
    )
    status = "PASS" if result.wasSuccessful() else "FAIL"
    markdown = "\n".join(
        [
            "# Unit Test Artifact",
            "",
            f"- Status: **{status}**",
            f"- Tests run: {result.testsRun}",
            f"- Failures: {len(result.failures)}",
            f"- Errors: {len(result.errors)}",
            f"- Skipped: {len(result.skipped)}",
            f"- Duration: {elapsed_seconds:.3f} seconds",
            f"- Created: {report['created_at_utc']}",
            "",
            "The complete runner output is in `unit_test_report.json`.",
            "",
        ]
    )
    (artifact_dir / "unit_test_report.md").write_text(markdown, encoding="utf-8")


def _run_unit_tests(artifact_dir: Path) -> bool:
    suite = unittest.defaultTestLoader.discover("tests")
    stream = io.StringIO()
    started = time.perf_counter()
    result = unittest.TextTestRunner(stream=stream, verbosity=2).run(suite)
    elapsed = time.perf_counter() - started
    output = stream.getvalue()
    print(output, end="")
    _write_test_artifact(artifact_dir, result, output, elapsed)
    return result.wasSuccessful()


def _run_experiment(artifact_dir: Path, episodes: int) -> bool:
    command = [
        sys.executable,
        "run_experiment.py",
        "--episodes",
        str(episodes),
        "--skip-rl",
        "--skip-meta",
        "--output",
        str(artifact_dir / "experiment_results.json"),
    ]
    completed = subprocess.run(command, capture_output=True, text=True)
    (artifact_dir / "experiment_run.tsv").write_text(
        completed.stdout + completed.stderr,
        encoding="utf-8",
    )
    print(completed.stdout, end="")
    if completed.stderr:
        print(completed.stderr, end="", file=sys.stderr)
    if completed.returncode == 0:
        _write_experiment_summary(artifact_dir, episodes)
    return completed.returncode == 0


def _write_experiment_summary(artifact_dir: Path, episodes: int) -> None:
    rows = json.loads((artifact_dir / "experiment_results.json").read_text(encoding="utf-8"))
    by_policy: dict[str, list[dict[str, object]]] = {}
    for row in rows:
        by_policy.setdefault(str(row["policy"]), []).append(row)

    def average(group: list[dict[str, object]], key: str) -> float:
        return sum(float(row[key]) for row in group) / len(group)

    lines = [
        "# Experiment Artifact",
        "",
        "Generated by run_tests.py after the unit tests passed.",
        "",
        f"- Matched evaluation episodes per task: {episodes}",
        "- Tasks: stable, variable, shock_prone",
        "- DP: balance bin 20, allocation grid 20",
        "- Test-run artifact mode: pooled Q-learning and Meta-RL are skipped for speed.",
        "- All amounts are synthetic simulation units.",
        "",
        "## Aggregate results",
        "",
        "| Policy | Mean reward | Goal attainment | Any shortfall | Mean shortfall |",
        "|---|---:|---:|---:|---:|",
    ]
    for policy in sorted(by_policy):
        group = by_policy[policy]
        lines.append(
            f"| {policy} | {average(group, 'total_reward'):.3f} | "
            f"{average(group, 'goal_attained') * 100:.1f}% | "
            f"{average(group, 'any_shortfall') * 100:.1f}% | "
            f"{average(group, 'shortfall_amount'):.2f} |"
        )
    lines.extend(
        [
            "",
            "Raw results: experiment_results.json",
            "Console output: experiment_run.tsv",
            "Unit test report: unit_test_report.md and unit_test_report.json",
            "",
        ]
    )
    (artifact_dir / "experiment_summary.md").write_text(
        "\n".join(lines),
        encoding="utf-8",
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--artifact-dir",
        type=Path,
        default=Path("artifacts"),
        help="directory for generated reports",
    )
    parser.add_argument(
        "--experiment",
        action="store_true",
        help="run the controlled DP comparison after tests pass",
    )
    parser.add_argument(
        "--episodes",
        type=int,
        default=5,
        help="matched episodes per task when --experiment is enabled",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.episodes <= 0:
        raise SystemExit("--episodes must be positive")
    args.artifact_dir.mkdir(parents=True, exist_ok=True)
    tests_ok = _run_unit_tests(args.artifact_dir)
    if not tests_ok:
        return 1
    if args.experiment and not _run_experiment(args.artifact_dir, args.episodes):
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
