"""Lightweight model-free baselines implemented with NumPy only.

PooledQPolicy is a tabular Q-learning baseline. RecurrentMetaPolicy is a small
recurrent policy-gradient agent. It is intentionally modest rather than a
full PPO implementation, which keeps the experiment runnable without
PyTorch while preserving the key Meta-RL test: one policy adapts its hidden
context from histories generated by different hidden task dynamics.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Sequence

import numpy as np

from .environment import (
    Action,
    EnvironmentConfig,
    GoalAllocationEnv,
    State,
    TaskType,
    Trajectory,
    available_surplus,
)


def action_catalog(config: EnvironmentConfig) -> tuple[Action, ...]:
    grid = config.action_grid
    max_units = max(0, config.max_action_cash // grid)
    return tuple(
        (e_units * grid, q_units * grid)
        for e_units in range(max_units + 1)
        for q_units in range(max_units - e_units + 1)
    )


def _state_key(state: State) -> tuple[int, ...]:
    return (
        state.t,
        state.wallet,
        state.reserve,
        state.goal,
        state.deadline,
        state.salary,
        state.fixed,
    )


class PooledQPolicy:
    """Tabular Q-learning over a mixture of hidden task types."""

    def __init__(
        self,
        tasks: Sequence[TaskType],
        config: EnvironmentConfig | None = None,
        seed: int = 0,
        learning_rate: float = 0.10,
        discount: float = 0.98,
        epsilon: float = 0.20,
        epsilon_decay: float = 0.995,
        epsilon_min: float = 0.02,
    ) -> None:
        self.tasks = tuple(tasks)
        self.config = config or EnvironmentConfig()
        self.rng = np.random.default_rng(seed)
        self.learning_rate = float(learning_rate)
        self.discount = float(discount)
        self.epsilon = float(epsilon)
        self.epsilon_decay = float(epsilon_decay)
        self.epsilon_min = float(epsilon_min)
        self.actions = action_catalog(self.config)
        self.action_index = {action: index for index, action in enumerate(self.actions)}
        self.q: dict[tuple[tuple[int, ...], int], float] = {}
        self.episode_returns: list[float] = []

    def reset(self, state: State | None = None) -> None:
        del state

    def _valid_indices(self, state: State) -> list[int]:
        surplus = available_surplus(state)
        return [
            index
            for index, (e, q) in enumerate(self.actions)
            if e + q <= surplus
        ]

    def _q_value(self, state: State, index: int) -> float:
        return self.q.get((_state_key(state), index), 0.0)

    def _select_index(self, state: State, stochastic: bool) -> int:
        valid = self._valid_indices(state)
        if not valid:
            return self.action_index[(0, 0)]
        if stochastic and self.rng.random() < self.epsilon:
            return int(self.rng.choice(np.asarray(valid)))
        values = np.asarray([self._q_value(state, index) for index in valid])
        best_value = float(np.max(values))
        best = [index for index, value in zip(valid, values) if np.isclose(value, best_value)]
        return int(self.rng.choice(np.asarray(best)))

    def act(self, state: State, stochastic: bool = False) -> Action:
        return self.actions[self._select_index(state, stochastic)]

    def observe(self, info: dict, next_state: State) -> None:
        del info, next_state

    def train(self, episodes: int = 2_000, seed: int | None = None) -> list[float]:
        if seed is not None:
            self.rng = np.random.default_rng(seed)
        for episode in range(int(episodes)):
            task = self.tasks[int(self.rng.integers(len(self.tasks)))]
            env = GoalAllocationEnv(task, self.config, seed=int(self.rng.integers(2**31 - 1)))
            state = env.reset()
            total = 0.0
            done = False
            while not done:
                index = self._select_index(state, stochastic=True)
                action = self.actions[index]
                next_state, reward, done, _ = env.step(action)
                current_key = (_state_key(state), index)
                if done:
                    bootstrap = 0.0
                else:
                    next_valid = self._valid_indices(next_state)
                    bootstrap = max(
                        (self._q_value(next_state, next_index) for next_index in next_valid),
                        default=0.0,
                    )
                old = self.q.get(current_key, 0.0)
                target = reward + self.discount * bootstrap
                self.q[current_key] = old + self.learning_rate * (target - old)
                state = next_state
                total += reward
            self.episode_returns.append(total)
            self.epsilon = max(self.epsilon_min, self.epsilon * self.epsilon_decay)
        return self.episode_returns


@dataclass
class _Record:
    features: np.ndarray
    previous_hidden: np.ndarray
    hidden: np.ndarray
    probabilities: np.ndarray
    valid_indices: tuple[int, ...]
    action_index: int
    reward: float


class RecurrentMetaPolicy:
    """A small recurrent policy-gradient Meta-RL prototype.

    The task identity is never given to the policy. During evaluation the
    hidden vector is reset once per episode and updated only from observed
    state, previous action outcome, and previous reward.
    """

    def __init__(
        self,
        tasks: Sequence[TaskType],
        config: EnvironmentConfig | None = None,
        seed: int = 0,
        hidden_size: int = 16,
        learning_rate: float = 0.002,
        discount: float = 0.98,
    ) -> None:
        self.tasks = tuple(tasks)
        self.config = config or EnvironmentConfig()
        self.rng = np.random.default_rng(seed)
        self.hidden_size = int(hidden_size)
        self.learning_rate = float(learning_rate)
        self.discount = float(discount)
        self.actions = action_catalog(self.config)
        self.action_index = {action: index for index, action in enumerate(self.actions)}
        self.feature_size = 10
        max_salary = max(
            value
            for task in self.tasks
            for value, _ in task.salary_outcomes()
        )
        max_expense = max(
            value
            for task in self.tasks
            for value, _ in task.expense_outcomes()
        )
        self.max_salary = max(1, max_salary)
        self.max_expense = max(1, max_expense)
        self.max_cash = max(
            1,
            self.config.max_action_cash,
            self.config.goal_target,
            self.config.reserve_target,
            self.config.initial_wallet,
            self.config.initial_reserve,
        )
        output_size = len(self.actions)
        scale = 1.0 / np.sqrt(self.hidden_size)
        self.w_input = self.rng.normal(0.0, scale, (self.hidden_size, self.feature_size))
        self.w_hidden = self.rng.normal(0.0, scale, (self.hidden_size, self.hidden_size))
        self.bias_hidden = np.zeros(self.hidden_size)
        self.w_output = self.rng.normal(0.0, scale, (output_size, self.hidden_size))
        self.bias_output = np.zeros(output_size)
        self.hidden = np.zeros(self.hidden_size)
        self.previous_expense = 0.0
        self.previous_reward = 0.0
        self.episode_returns: list[float] = []

    def reset(self, state: State | None = None) -> None:
        del state
        self.hidden = np.zeros(self.hidden_size)
        self.previous_expense = 0.0
        self.previous_reward = 0.0

    def _features(self, state: State) -> np.ndarray:
        return np.asarray(
            [
                state.t / max(1, self.config.horizon),
                state.wallet / self.max_cash,
                state.reserve / self.max_cash,
                state.goal / max(1, self.config.goal_target),
                state.deadline / max(1, self.config.deadline),
                state.salary / self.max_salary,
                state.fixed / self.max_salary,
                available_surplus(state) / self.max_cash,
                self.previous_expense / self.max_expense,
                np.tanh(self.previous_reward / 10.0),
            ],
            dtype=float,
        )

    def _valid_indices(self, state: State) -> tuple[int, ...]:
        surplus = available_surplus(state)
        return tuple(
            index
            for index, (e, q) in enumerate(self.actions)
            if e + q <= surplus
        )

    @staticmethod
    def _masked_softmax(logits: np.ndarray, valid: tuple[int, ...]) -> np.ndarray:
        probabilities = np.zeros_like(logits, dtype=float)
        if not valid:
            return probabilities
        valid_array = np.asarray(valid, dtype=int)
        shifted = logits[valid_array] - np.max(logits[valid_array])
        exp_values = np.exp(np.clip(shifted, -50.0, 50.0))
        probabilities[valid_array] = exp_values / np.sum(exp_values)
        return probabilities

    def _forward(
        self,
        state: State,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, tuple[int, ...]]:
        features = self._features(state)
        previous_hidden = self.hidden.copy()
        hidden = np.tanh(
            self.w_input @ features + self.w_hidden @ previous_hidden + self.bias_hidden
        )
        logits = self.w_output @ hidden + self.bias_output
        valid = self._valid_indices(state)
        probabilities = self._masked_softmax(logits, valid)
        self.hidden = hidden
        return features, previous_hidden, hidden, probabilities, valid

    def act(self, state: State, stochastic: bool = False) -> Action:
        _, _, _, probabilities, valid = self._forward(state)
        if not valid:
            return (0, 0)
        valid_array = np.asarray(valid, dtype=int)
        if stochastic:
            index = int(self.rng.choice(valid_array, p=probabilities[valid_array]))
        else:
            values = probabilities[valid_array]
            index = int(valid_array[int(np.argmax(values))])
        return self.actions[index]

    def observe(self, info: dict, next_state: State) -> None:
        del next_state
        self.previous_expense = float(info.get("expense", 0.0))
        self.previous_reward = float(info.get("reward", 0.0))

    def _rollout(
        self,
        task: TaskType,
        seed: int,
        trajectory: Trajectory | None = None,
        stochastic: bool = True,
    ) -> tuple[list[_Record], float]:
        env = GoalAllocationEnv(task, self.config, seed=seed)
        state = env.reset(trajectory=trajectory)
        self.reset(state)
        records: list[_Record] = []
        done = False
        total = 0.0
        while not done:
            features, previous_hidden, hidden, probabilities, valid = self._forward(state)
            valid_array = np.asarray(valid, dtype=int)
            if stochastic:
                index = int(self.rng.choice(valid_array, p=probabilities[valid_array]))
            else:
                index = int(valid_array[np.argmax(probabilities[valid_array])])
            action = self.actions[index]
            next_state, reward, done, info = env.step(action)
            records.append(
                _Record(
                    features=features,
                    previous_hidden=previous_hidden,
                    hidden=hidden,
                    probabilities=probabilities,
                    valid_indices=valid,
                    action_index=index,
                    reward=reward,
                )
            )
            self.observe(info, next_state)
            state = next_state
            total += reward
        return records, total

    def train(self, episodes: int = 2_000, seed: int | None = None) -> list[float]:
        if seed is not None:
            self.rng = np.random.default_rng(seed)
        for _ in range(int(episodes)):
            task = self.tasks[int(self.rng.integers(len(self.tasks)))]
            records, total = self._rollout(
                task,
                seed=int(self.rng.integers(2**31 - 1)),
                stochastic=True,
            )
            returns = np.zeros(len(records), dtype=float)
            running = 0.0
            for index in range(len(records) - 1, -1, -1):
                running = records[index].reward + self.discount * running
                returns[index] = running
            advantages = returns - float(np.mean(returns))
            advantage_scale = float(np.std(advantages))
            if advantage_scale > 1e-9:
                advantages /= advantage_scale

            grad_input = np.zeros_like(self.w_input)
            grad_hidden = np.zeros_like(self.w_hidden)
            grad_bias_hidden = np.zeros_like(self.bias_hidden)
            grad_output = np.zeros_like(self.w_output)
            grad_bias_output = np.zeros_like(self.bias_output)
            hidden_gradient_from_future = np.zeros(self.hidden_size)
            for record, advantage in zip(reversed(records), reversed(advantages)):
                policy_gradient = np.zeros(len(self.actions), dtype=float)
                valid_array = np.asarray(record.valid_indices, dtype=int)
                policy_gradient[valid_array] = -record.probabilities[valid_array]
                policy_gradient[record.action_index] += 1.0
                policy_gradient *= advantage
                grad_output += np.outer(policy_gradient, record.hidden)
                grad_bias_output += policy_gradient
                hidden_gradient = self.w_output.T @ policy_gradient + hidden_gradient_from_future
                preactivation_gradient = hidden_gradient * (1.0 - record.hidden**2)
                grad_input += np.outer(preactivation_gradient, record.features)
                grad_hidden += np.outer(preactivation_gradient, record.previous_hidden)
                grad_bias_hidden += preactivation_gradient
                hidden_gradient_from_future = self.w_hidden.T @ preactivation_gradient

            all_gradients = [
                grad_input,
                grad_hidden,
                grad_bias_hidden,
                grad_output,
                grad_bias_output,
            ]
            norm = float(np.sqrt(sum(np.sum(gradient**2) for gradient in all_gradients)))
            if norm > 5.0:
                scale = 5.0 / norm
                all_gradients = [gradient * scale for gradient in all_gradients]
            self.w_input += self.learning_rate * all_gradients[0]
            self.w_hidden += self.learning_rate * all_gradients[1]
            self.bias_hidden += self.learning_rate * all_gradients[2]
            self.w_output += self.learning_rate * all_gradients[3]
            self.bias_output += self.learning_rate * all_gradients[4]
            self.episode_returns.append(total)
        return self.episode_returns
